os:
  - linux
services:
  - docker
language: java
node_js:
  - "4.5.0"
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - node
    - node_modules
    - $HOME/.gradle
env:
  - NODE_VERSION=4.5.0
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - ./gradlew clean
  - ./gradlew test
  - gulp test
  - ./gradlew bootRepackage -Pprod buildDocker -x test
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag pizzalab 4lexnz/pizzalab:latest
  - docker push 4lexnz/pizzalab:latest
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
